import type { ApplianceType, DietaryTag, DietaryPreference } from './appliances-data'

export type { ApplianceType, DietaryTag, DietaryPreference }

export type SubjectColor = 1 | 2 | 3 | 4 | 5

export type ClassEntry = {
  id: string
  subject: string
  code: string
  instructor: string
  room: string
  days: string[]
  start: string
  end: string
  color: SubjectColor
  confidence?: 'high' | 'low'
  lowFields?: string[]
}

export const classes: ClassEntry[] = [
  {
    id: 'math101',
    subject: 'Calculus I',
    code: 'MATH 101',
    instructor: 'Dr. Elena Reyes',
    room: 'Sci Hall 204',
    days: ['Mon', 'Wed', 'Fri'],
    start: '08:30',
    end: '09:50',
    color: 1,
    confidence: 'high',
  },
  {
    id: 'chem120',
    subject: 'General Chemistry',
    code: 'CHEM 120',
    instructor: 'Prof. Marcus Hale',
    room: 'Lab B-12',
    days: ['Mon', 'Wed'],
    start: '10:15',
    end: '12:00',
    color: 2,
    confidence: 'low',
    lowFields: ['room'],
  },
  {
    id: 'eng205',
    subject: 'Modern Literature',
    code: 'ENG 205',
    instructor: 'Dr. Aiko Tanaka',
    room: 'Humanities 310',
    days: ['Tue', 'Thu'],
    start: '09:00',
    end: '10:20',
    color: 3,
    confidence: 'high',
  },
  {
    id: 'cs150',
    subject: 'Intro to Programming',
    code: 'CS 150',
    instructor: 'Prof. Danielle Okonkwo',
    room: 'Tech Center 118',
    days: ['Tue', 'Thu'],
    start: '13:00',
    end: '14:40',
    color: 4,
    confidence: 'low',
    lowFields: ['instructor'],
  },
  {
    id: 'psy110',
    subject: 'Psychology 101',
    code: 'PSY 110',
    instructor: 'Dr. Samir Patel',
    room: 'West Wing 22',
    days: ['Mon', 'Fri'],
    start: '15:00',
    end: '16:20',
    color: 5,
    confidence: 'high',
  },
  {
    id: 'phe100',
    subject: 'Fitness & Wellness',
    code: 'PHE 100',
    instructor: 'Coach Riley Brooks',
    room: 'Gym A',
    days: ['Sat'],
    start: '10:00',
    end: '11:30',
    color: 2,
    confidence: 'high',
  },
]

export const weekDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

export const rawScheduleSample = `MATH101 calculus 1 MWF 8:30-9:50am sci hall 204 reyes
chem 120 - general chem lab, mon/wed 10:15 to 12, lab b12
ENG205 modern lit TTh 9-10:20 humanities 310 (tanaka)
cs150 intro programming tues thurs 1pm-2:40pm tech center 118
psy 110 mon fri 3:00-4:20 west wing 22 dr patel
phe100 fitness sat 10-11:30 gym a`

export type Alarm = {
  id: string
  classId: string
  subject: string
  code: string
  time: string
  day: string
  lead: 15 | 30 | 60
  enabled: boolean
  color: SubjectColor
}

export const alarms: Alarm[] = [
  {
    id: 'a1',
    classId: 'math101',
    subject: 'Calculus I',
    code: 'MATH 101',
    time: '08:30',
    day: 'Today',
    lead: 30,
    enabled: true,
    color: 1,
  },
  {
    id: 'a2',
    classId: 'chem120',
    subject: 'General Chemistry',
    code: 'CHEM 120',
    time: '10:15',
    day: 'Today',
    lead: 15,
    enabled: true,
    color: 2,
  },
  {
    id: 'a3',
    classId: 'psy110',
    subject: 'Psychology 101',
    code: 'PSY 110',
    time: '15:00',
    day: 'Today',
    lead: 60,
    enabled: false,
    color: 5,
  },
  {
    id: 'a4',
    classId: 'eng205',
    subject: 'Modern Literature',
    code: 'ENG 205',
    time: '09:00',
    day: 'Tomorrow',
    lead: 30,
    enabled: true,
    color: 3,
  },
  {
    id: 'a5',
    classId: 'cs150',
    subject: 'Intro to Programming',
    code: 'CS 150',
    time: '13:00',
    day: 'Tomorrow',
    lead: 15,
    enabled: true,
    color: 4,
  },
]

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack'

export type Recipe = {
  slug: string
  title: string
  image: string
  minutes: number
  servings: number
  cost: string
  costUSD: number
  difficulty: 'Easy' | 'Medium'
  appliance: 'Microwave' | 'Rice cooker' | 'No cook' | 'Kettle' | 'Hot plate'
  meal: 'Breakfast' | 'Lunch' | 'Dinner' | 'Snack'
  mealType: MealType
  mealTypes?: MealType[]
  blurb: string
  ingredients: string[]
  steps: string[]
  tip: string
  cuisine_region?: string
  requiredAppliances?: ApplianceType[]
  dietary_tags?: DietaryTag[]
  countryTags?: string[]
}

export const recipes: Recipe[] = [
  // ─── BREAKFAST ───────────────────────────────────────────────────────────────
  {
    slug: 'champorado-chocolate-rice',
    title: 'Warm Champorado',
    image: '/recipes/champorado-chocolate-rice.jpg',
    minutes: 8,
    servings: 1,
    cost: '$0.80',
    costUSD: 0.80,
    difficulty: 'Easy',
    appliance: 'Microwave',
    meal: 'Breakfast',
    mealType: 'breakfast',
    blurb: 'Filipino sweet cocoa rice porridge with a drizzle of condensed milk.',
    requiredAppliances: ['microwave'],
    dietary_tags: ['vegetarian', 'halal'],
    countryTags: ['PH'],
    ingredients: [
      '1/2 cup cooked white rice',
      '2 tbsp cocoa powder or unsweetened tablea',
      '2 tbsp sugar',
      '1/2 cup water or milk',
      'Evaporated or condensed milk for drizzle',
    ],
    steps: [
      'In a large microwave-safe mug, combine cooked rice, cocoa powder, sugar, and water.',
      'Stir well and microwave on high for 2 minutes until hot and thickened.',
      'Let sit 1 minute to thicken further, then top with a generous drizzle of milk.',
    ],
    tip: 'Using leftover cooked rice cuts cooking time from 30 minutes to just 2 minutes in a dorm microwave!',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'sinangag-garlic-rice-egg',
    title: 'Sinangag at Itlog (Garlic Rice & Egg)',
    image: '/recipes/sinangag-garlic-rice-egg.jpg',
    minutes: 6,
    servings: 1,
    cost: '$0.75',
    costUSD: 0.75,
    difficulty: 'Easy',
    appliance: 'Microwave',
    meal: 'Breakfast',
    mealType: 'breakfast',
    mealTypes: ['breakfast', 'dinner'],
    blurb: 'The classic leftover-rice fix — garlic fried rice topped with a fried or scrambled egg.',
    requiredAppliances: ['microwave', 'induction_burner'],
    dietary_tags: ['vegetarian', 'halal'],
    countryTags: ['PH'],
    ingredients: [
      '1 cup day-old cold rice',
      '3 cloves garlic, minced',
      '1 egg',
      '1 tbsp oil or butter',
      'Pinch of salt and black pepper',
    ],
    steps: [
      'Sauté minced garlic in oil or butter until golden and fragrant.',
      'Add cold rice, breaking up clumps, and toss with garlic and salt for 3 minutes.',
      'Push rice to the side, crack in the egg, and scramble or fry to desired doneness.',
    ],
    tip: 'Day-old cold rice from the mini fridge is essential — fresh warm rice will turn soggy instead of crisping up in garlic oil.',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'monay-with-egg',
    title: 'Monay / Pandesal with Egg',
    image: '/recipes/monay-with-egg.jpg',
    minutes: 4,
    servings: 1,
    cost: '$0.65',
    costUSD: 0.65,
    difficulty: 'Easy',
    appliance: 'Microwave',
    meal: 'Breakfast',
    mealType: 'breakfast',
    blurb: 'Toasted Filipino bread stuffed with a fried or microwaved egg & melted cheese.',
    requiredAppliances: ['microwave'],
    dietary_tags: ['vegetarian', 'halal'],
    countryTags: ['PH'],
    ingredients: [
      '1 fresh monay or 2 pandesal bread rolls',
      '1 egg',
      '1 tsp butter or margarine',
      '1 slice cheese or optional slice of luncheon meat',
    ],
    steps: [
      'Beat egg in a microwave-safe mug with salt, pepper, and butter.',
      'Microwave on high for 45 seconds until fluffed and set.',
      'Slice bread roll horizontally, insert egg and cheese, and warm in microwave for 10 seconds.',
    ],
    tip: 'Splitting and microwaving the bread with cheese for 10 seconds softens the dense crumb and melts the cheese into the warm egg. You can add a slice of fried luncheon meat for extra protein!',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'rice-cooker-lugaw',
    title: 'Lugaw / Arroz Caldo (Simplified)',
    image: '/recipes/rice-cooker-lugaw.jpg',
    minutes: 25,
    servings: 2,
    cost: '$0.90',
    costUSD: 0.90,
    difficulty: 'Easy',
    appliance: 'Rice cooker',
    meal: 'Breakfast',
    mealType: 'breakfast',
    mealTypes: ['breakfast', 'lunch'],
    blurb: 'Simple rice porridge with ginger and scallion — add a boiled egg or leftover chicken if you have it.',
    requiredAppliances: ['rice_cooker'],
    dietary_tags: ['vegetarian', 'halal'],
    countryTags: ['PH'],
    ingredients: [
      '1/2 cup white rice, rinsed',
      '3.5 cups water or vegetable stock',
      '1 thumb ginger, sliced thin',
      '2 cloves garlic, crushed',
      '1 hard-boiled egg & chopped scallions',
    ],
    steps: [
      'Add rice, water/stock, ginger, and garlic to the rice cooker pot.',
      'Press Cook and let simmer until thick and creamy (approx 20 mins).',
      'Ladle into a mug or bowl, top with sliced boiled egg, scallions, and a squeeze of calamansi.',
    ],
    tip: 'Base version is 100% vegetarian — add leftover rotisserie chicken or a dash of fish sauce if you want traditional Arroz Caldo flavor!',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'taho-overnight-oats',
    title: 'Taho-Style Overnight Oats',
    image: '/recipes/taho-overnight-oats.jpg',
    minutes: 5,
    servings: 1,
    cost: '$0.75',
    costUSD: 0.75,
    difficulty: 'Easy',
    appliance: 'No cook',
    meal: 'Breakfast',
    mealType: 'breakfast',
    blurb: "No-cook oats soaked overnight in milk with a drizzle of brown sugar syrup — Champorado's cousin, ready when you wake up.",
    requiredAppliances: [],
    dietary_tags: ['vegetarian', 'halal'],
    countryTags: ['PH'],
    ingredients: [
      '1/2 cup rolled oats',
      '1/2 cup milk or soy milk',
      '2 tbsp brown sugar syrup (arnibal)',
      '1 tbsp sago tapioca pearls or chia seeds',
    ],
    steps: [
      'In a glass jar, combine oats, milk, and brown sugar syrup.',
      'Stir well, seal, and refrigerate overnight (at least 6 hours).',
      'Top with warm brown sugar drizzle and sago pearls right before running out to class.',
    ],
    tip: 'Simmer brown sugar with equal parts water for 2 minutes to create homemade arnibal syrup that lasts 2 weeks in your dorm fridge!',
    cuisine_region: 'Filipino',
  },

  // ─── LUNCH ─────────────────────────────────────────────────────────────────
  {
    slug: 'quick-chicken-adobo-bowl',
    title: 'Dorm-Style Chicken Adobo',
    image: '/recipes/quick-chicken-adobo-bowl.jpg',
    minutes: 15,
    servings: 1,
    cost: '$1.80',
    costUSD: 1.80,
    difficulty: 'Easy',
    appliance: 'Hot plate',
    meal: 'Lunch',
    mealType: 'lunch',
    mealTypes: ['lunch', 'dinner'],
    blurb: 'One-pot chicken adobo — soy sauce, vinegar, and garlic, no marinating required.',
    requiredAppliances: ['induction_burner', 'rice_cooker'],
    dietary_tags: ['halal', 'contains_meat'],
    countryTags: ['PH'],
    ingredients: [
      '150g boneless chicken thigh, diced',
      '2 tbsp soy sauce',
      '1.5 tbsp white vinegar',
      '3 cloves garlic, crushed',
      '1 bay leaf & black peppercorns',
      'Warm steamed rice',
    ],
    steps: [
      'Combine chicken, soy sauce, garlic, bay leaf, and pepper in a small saucepan over medium heat.',
      'Simmer for 8 minutes until chicken is cooked through.',
      'Pour in vinegar and let bubble uncovered for 3 minutes without stirring.',
      'Serve sizzling over a hot bowl of rice.',
    ],
    tip: 'Do not stir right after adding vinegar — letting it boil untouched burns off harsh acidity and leaves a smooth tangy glaze.',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'corned-beef-rice-bowl',
    title: 'Corned Beef Rice Bowl',
    image: '/recipes/corned-beef-rice-bowl.jpg',
    minutes: 8,
    servings: 1,
    cost: '$1.40',
    costUSD: 1.40,
    difficulty: 'Easy',
    appliance: 'Hot plate',
    meal: 'Lunch',
    mealType: 'lunch',
    countryTags: ['PH'],
    blurb: 'Canned corned beef fried with garlic and onion, served over rice — a budget dorm staple.',
    requiredAppliances: ['induction_burner', 'microwave'],
    dietary_tags: ['halal', 'contains_meat'],
    ingredients: [
      '1/2 can corned beef',
      '1/2 small onion, sliced',
      '2 cloves garlic, minced',
      '1 cup warm rice',
      '1 tsp oil',
    ],
    steps: [
      'Sauté garlic and onion in oil over medium heat until fragrant.',
      'Add corned beef and cook for 4 minutes until crispy at the edges.',
      'Spoon hot corned beef over warm rice.',
    ],
    tip: 'Let the corned beef sit untouched in the hot pan for 2 minutes to get those delicious crispy caramelized bits!',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'sinigang-mug-soup',
    title: 'Quick Sinigang (Packet-Based)',
    image: '/recipes/sinigang-mug-soup.jpg',
    minutes: 6,
    servings: 1,
    cost: '$1.25',
    costUSD: 1.25,
    difficulty: 'Easy',
    appliance: 'Kettle',
    meal: 'Lunch',
    mealType: 'lunch',
    countryTags: ['PH'],
    blurb: 'Instant sinigang mix with vegetables and your choice of protein — ready in 20–30 minutes.',
    requiredAppliances: ['kettle', 'induction_burner'],
    dietary_tags: ['contains_meat', 'contains_pork'],
    ingredients: [
      '1 tsp instant sinigang tamarind mix',
      '300ml boiling water',
      'Handful of spinach or kangkong',
      '4 slices tomato & radish',
      'Pre-cooked pork, shrimp, or cubed firm tofu',
    ],
    steps: [
      'Boil water in a kettle and dissolve sinigang mix in a deep heatproof bowl.',
      'Add sliced tomatoes, radish, and pre-cooked meat or tofu.',
      'Cover with a plate for 4 minutes until veggies soften, then stir in green spinach.',
    ],
    tip: 'Swap in cubed firm tofu instead of pork for a fast 100% vegetarian sinigang broth!',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'tortang-talong-omelet',
    title: 'Tortang Talong (Eggplant Omelet)',
    image: '/recipes/tortang-talong-omelet.jpg',
    minutes: 12,
    servings: 1,
    cost: '$0.95',
    costUSD: 0.95,
    difficulty: 'Easy',
    appliance: 'Hot plate',
    meal: 'Lunch',
    mealType: 'lunch',
    countryTags: ['PH'],
    blurb: 'Eggplant omelet — a quick, filling one-pan lunch.',
    requiredAppliances: ['induction_burner'],
    dietary_tags: ['vegetarian', 'halal'],
    ingredients: [
      '1 small Chinese eggplant',
      '2 eggs, beaten',
      '1 clove garlic, minced',
      'Salt and black pepper',
      '1 tbsp oil for frying',
    ],
    steps: [
      'Broil or microwave eggplant for 3 minutes until soft, then peel off skin keeping stem intact.',
      'Flatten eggplant with a fork, dip thoroughly into beaten egg mixture with salt and pepper.',
      'Fry in hot oil for 3 minutes per side until golden brown.',
    ],
    tip: 'Tortang Talong is 100% vegetarian. You can also mix in seasoned ground pork (Tortang Giniling variant) if you have meat on hand!',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'instant-pancit-canton-egg',
    title: 'Instant Pancit Canton + Egg & Veggies',
    image: '/recipes/instant-pancit-canton-egg.jpg',
    minutes: 7,
    servings: 1,
    cost: '$0.85',
    costUSD: 0.85,
    difficulty: 'Easy',
    appliance: 'Kettle',
    meal: 'Lunch',
    mealType: 'lunch',
    countryTags: ['PH'],
    blurb: 'Dressed-up instant pancit canton with a fried egg and whatever vegetables you have on hand.',
    requiredAppliances: ['kettle', 'microwave'],
    dietary_tags: ['vegetarian', 'halal'],
    ingredients: [
      '1 pack instant pancit canton (chilimansi or sweet & spicy)',
      '1 egg',
      'Handful of shredded cabbage or carrots',
      'Boiling water from kettle',
    ],
    steps: [
      'Soak noodles and veggies in boiling kettle water for 3 minutes, then drain thoroughly.',
      'Mix flavor packets in a plate, then toss in drained hot noodles.',
      'Top with a microwave-poached or fried egg.',
    ],
    tip: 'Add a drizzle of sesame oil or calamansi juice to elevate cheap instant noodles into a bistro-level meal.',
    cuisine_region: 'Filipino',
  },

  // ─── DINNER ────────────────────────────────────────────────────────────────
  {
    slug: 'dorm-simple-menudo',
    title: 'Menudo (Simplified)',
    image: '/recipes/dorm-simple-menudo.jpg',
    minutes: 20,
    servings: 2,
    cost: '$1.90',
    costUSD: 1.90,
    difficulty: 'Easy',
    appliance: 'Hot plate',
    meal: 'Dinner',
    mealType: 'dinner',
    mealTypes: ['dinner', 'lunch'],
    blurb: 'Diced pork or chicken with tomato sauce, potato, and carrot — a simplified one-pot menudo.',
    requiredAppliances: ['induction_burner', 'rice_cooker'],
    dietary_tags: ['contains_meat', 'contains_pork'],
    countryTags: ['PH'],
    ingredients: [
      '150g pork shoulder or chicken, diced small',
      '1/2 cup tomato sauce',
      '1 potato & 1 carrot, diced small',
      '1 hotdog, sliced',
      '2 cloves garlic & 1/2 onion',
    ],
    steps: [
      'Sauté garlic and onion in pan or rice cooker pot until soft.',
      'Add pork/chicken and cook 5 minutes until browned.',
      'Add potato, carrot, hotdog, and tomato sauce with 1/4 cup water.',
      'Simmer covered for 10 minutes until potatoes are tender.',
    ],
    tip: 'Dicing potatoes and meat small (<1cm) cuts cook time in half so it boils tender in under 15 minutes!',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'ginisang-munggo-stew',
    title: 'Ginisang Munggo (Mung Bean Stew)',
    image: '/recipes/ginisang-munggo-stew.jpg',
    minutes: 30,
    servings: 2,
    cost: '$0.85',
    costUSD: 0.85,
    difficulty: 'Easy',
    appliance: 'Rice cooker',
    meal: 'Dinner',
    mealType: 'dinner',
    countryTags: ['PH'],
    blurb: 'Cheap, filling mung bean stew — add malunggay or leftover vegetables if you have them.',
    requiredAppliances: ['rice_cooker', 'induction_burner'],
    dietary_tags: ['vegetarian', 'halal'],
    ingredients: [
      '1/2 cup green mung beans, pre-soaked',
      '2.5 cups water',
      '2 cloves garlic & 1 small onion',
      '1 tomato, chopped',
      'Handful of spinach or malunggay leaves',
    ],
    steps: [
      'Boil pre-soaked mung beans in rice cooker with water for 20 minutes until soft.',
      'Sauté garlic, onion, and tomato in a separate cup or pot, then stir into mung beans.',
      'Season with salt or soy sauce, and stir in spinach right before serving.',
    ],
    tip: 'Pre-soaking mung beans in hot water for 30 minutes while studying cuts the rice cooker boiling time to under 20 minutes!',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'garlic-rice-egg-dinner',
    title: 'Fried Rice + Egg Remix',
    image: '/recipes/garlic-rice-egg-dinner.jpg',
    minutes: 7,
    servings: 1,
    cost: '$0.85',
    costUSD: 0.85,
    difficulty: 'Easy',
    appliance: 'Microwave',
    meal: 'Dinner',
    mealType: 'dinner',
    mealTypes: ['dinner', 'breakfast'],
    blurb: 'Same base as breakfast sinangag, repositioned as a lazy, filling dinner.',
    requiredAppliances: ['microwave', 'induction_burner'],
    dietary_tags: ['vegetarian', 'halal'],
    countryTags: ['PH'],
    ingredients: [
      '1.5 cups cold steamed rice',
      '2 tbsp fried garlic chips',
      '1 egg',
      '1 tbsp soy sauce',
      '1 tsp butter or oil',
    ],
    steps: [
      'Warm rice in microwave for 60 seconds with soy sauce and butter.',
      'Top with crispy fried garlic chips.',
      'Add a poached or sunny-side-up egg and mix into hot rice for a creamy finish.',
    ],
    tip: 'Store a jar of pre-made fried garlic chips in your dorm room for instant aroma on any late-night rice bowl!',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'chicken-tinola-soup',
    title: 'Chicken Tinola (Light Version)',
    image: '/recipes/chicken-tinola-soup.jpg',
    minutes: 18,
    servings: 1,
    cost: '$1.60',
    costUSD: 1.60,
    difficulty: 'Easy',
    appliance: 'Kettle',
    meal: 'Dinner',
    mealType: 'dinner',
    countryTags: ['PH'],
    blurb: "Ginger chicken soup with sayote or papaya — good comfort food when you're not feeling well.",
    requiredAppliances: ['kettle', 'induction_burner'],
    dietary_tags: ['contains_meat', 'halal'],
    ingredients: [
      '150g chicken breast or thigh, thinly sliced',
      '1 thumb ginger, sliced into matchsticks',
      '1/2 sayote or green papaya, wedged',
      '300ml water + 1 tsp fish sauce (patis)',
      'Handful of spinach or chili leaves',
    ],
    steps: [
      'Boil water and ginger in kettle or pot to create ginger broth.',
      'Add thin chicken slices and sayote wedges; simmer for 10 minutes until chicken is white and sayote is tender.',
      'Season with fish sauce and stir in spinach leaves for 1 minute.',
    ],
    tip: 'Thinly slicing the chicken breast allows it to cook through completely in boiling ginger broth within 8 minutes!',
    cuisine_region: 'Filipino',
  },
  {
    slug: 'luncheon-meat-rice-bowl',
    title: 'Spam / Luncheon Meat Musubi Rice',
    image: '/recipes/luncheon-meat-rice-bowl.jpg',
    minutes: 6,
    servings: 1,
    cost: '$1.50',
    costUSD: 1.50,
    difficulty: 'Easy',
    appliance: 'Hot plate',
    meal: 'Dinner',
    mealType: 'dinner',
    countryTags: ['PH'],
    blurb: 'Fried luncheon meat over rice, wrapped in nori — a no-fuss protein fix.',
    requiredAppliances: ['induction_burner', 'microwave'],
    dietary_tags: ['contains_meat', 'contains_pork'],
    ingredients: [
      '2 thick slices canned luncheon meat (Spam)',
      '1 cup warm rice',
      '1 tbsp soy sauce + 1 tsp sugar (optional glaze)',
      '1 sheet nori seaweed (optional)',
    ],
    steps: [
      'Sear luncheon meat slices in a dry pan over high heat for 2 minutes per side until caramelized.',
      'Drizzle with soy-sugar glaze if desired.',
      'Place over warm rice and wrap with a strip of crispy nori seaweed.',
    ],
    tip: 'Luncheon meat has enough natural fat that you don’t need any oil in the pan — just sear on medium-high until crispy!',
    cuisine_region: 'Filipino',
  },

  // ─── OTHER REGIONAL DORM RECIPES ─────────────────────────────────────────────
  {
    slug: 'tamago-kake-gohan',
    title: 'Tamago Kake Gohan (TKG)',
    image: '/recipes/tamago-kake-gohan.jpg',
    minutes: 3,
    servings: 1,
    cost: '$0.70',
    costUSD: 0.70,
    difficulty: 'Easy',
    appliance: 'No cook',
    meal: 'Breakfast',
    mealType: 'breakfast',
    countryTags: ['JP'],
    blurb: 'Iconic Japanese comfort breakfast: hot rice whipped with fresh egg and soy sauce.',
    requiredAppliances: [],
    dietary_tags: ['vegetarian', 'halal'],
    ingredients: [
      '1 bowl steaming hot rice',
      '1 fresh pasteurized egg',
      '1 tsp soy sauce or dashi soy',
      'Furikake or nori strips',
    ],
    steps: [
      'Crack egg into hot rice bowl.',
      'Add soy sauce and whip vigorously with chopsticks for 30 seconds until foamy and custard-like.',
      'Top with furikake seasoning.',
    ],
    tip: 'The rice must be steaming hot so it lightly cooks the whipped egg into a creamy sauce.',
    cuisine_region: 'Japanese',
  },
  {
    slug: 'kimchi-fried-rice-mug',
    title: 'Dorm Kimchi Fried Rice',
    image: '/recipes/kimchi-fried-rice-mug.jpg',
    minutes: 5,
    servings: 1,
    cost: '$1.30',
    costUSD: 1.30,
    difficulty: 'Easy',
    appliance: 'Microwave',
    meal: 'Lunch',
    mealType: 'lunch',
    mealTypes: ['lunch', 'dinner'],
    countryTags: ['KR', 'PH'],
    blurb: 'Spicy Korean fried rice loaded with tangy kimchi and sesame oil.',
    requiredAppliances: ['microwave'],
    dietary_tags: ['vegetarian', 'halal'],
    ingredients: [
      '1 cup cooked rice',
      '1/3 cup chopped kimchi + 1 tbsp kimchi juice',
      '1 tsp gochujang (Korean chili paste)',
      '1 tsp sesame oil',
      '1 egg',
    ],
    steps: [
      'Mix rice, kimchi, juice, gochujang, and sesame oil in a bowl.',
      'Microwave for 2 minutes until hot.',
      'Top with a microwave-steamed or kettle egg and scallions.',
    ],
    tip: 'Add a slice of American cheese on top for instant Korean cheese kimchi bokkeumbap!',
    cuisine_region: 'Korean',
  },
  {
    slug: 'microwave-mug-pancakes',
    title: 'Microwave Mug Pancakes',
    image: '/recipes/microwave-mug-pancakes.jpg',
    minutes: 4,
    servings: 1,
    cost: '$0.90',
    costUSD: 0.90,
    difficulty: 'Easy',
    appliance: 'Microwave',
    meal: 'Breakfast',
    mealType: 'breakfast',
    countryTags: ['US', 'PH'],
    blurb: 'Fluffy stack energy, zero pan, zero cleanup.',
    requiredAppliances: ['microwave'],
    dietary_tags: ['vegetarian', 'halal'],
    ingredients: [
      '4 tbsp all-purpose flour',
      '1 tbsp sugar',
      '1/2 tsp baking powder',
      'Pinch of salt',
      '3 tbsp milk',
      '1 tsp oil or melted butter',
      'Maple syrup + berries to finish',
    ],
    steps: [
      'Whisk flour, sugar, baking powder and salt directly in a large mug.',
      'Pour in the milk and oil. Stir until just combined — a few lumps are fine.',
      'Microwave on high for 70–90 seconds. Stop as soon as the top is set.',
      'Let it rest 1 minute, then top with syrup and berries.',
    ],
    tip: 'Use a mug at least 350ml — the batter doubles in height while cooking and a small mug will overflow onto the microwave plate.',
    cuisine_region: 'American',
  },
  {
    slug: 'rice-cooker-congee',
    title: 'Rice Cooker Congee',
    image: '/recipes/rice-cooker-congee.jpg',
    minutes: 45,
    servings: 2,
    cost: '$1.40',
    costUSD: 1.40,
    difficulty: 'Easy',
    appliance: 'Rice cooker',
    meal: 'Dinner',
    mealType: 'dinner',
    countryTags: ['JP', 'KR'],
    blurb: 'Set it, forget it, come back to comfort food.',
    requiredAppliances: ['rice_cooker'],
    dietary_tags: ['halal', 'contains_meat'],
    ingredients: [
      '1/2 cup jasmine rice, rinsed',
      '4 cups water or stock',
      '1 tsp salt',
      '1 thumb ginger, sliced',
      '1 egg',
      'Scallions, sesame oil, soy sauce',
    ],
    steps: [
      'Rinse the rice until the water runs mostly clear, then add it to the rice cooker.',
      'Add water, salt and ginger. Run the porridge setting, or the normal cycle twice.',
      'Stir once halfway through so the rice does not stick to the base.',
      'Crack an egg into the hot congee and stir for 30 seconds until silky.',
      'Finish with scallions, a few drops of sesame oil and soy sauce.',
    ],
    tip: 'Keep the lid vent clear of the wall — congee foams more than rice and can spit starchy water down the back of your desk.',
    cuisine_region: 'Asian',
  },
  {
    slug: 'no-cook-overnight-oats',
    title: 'No-Cook Overnight Oats',
    image: '/recipes/overnight-oats.jpg',
    minutes: 5,
    servings: 1,
    cost: '$0.75',
    costUSD: 0.75,
    difficulty: 'Easy',
    appliance: 'No cook',
    meal: 'Breakfast',
    mealType: 'breakfast',
    countryTags: ['US'],
    blurb: 'Built at midnight, eaten on the walk to an 8:30.',
    requiredAppliances: [],
    dietary_tags: ['vegetarian', 'halal'],
    ingredients: [
      '1/2 cup rolled oats',
      '1/2 cup milk or yogurt',
      '1 tsp chia seeds',
      '1 tsp honey',
      'Banana slices and berries',
    ],
    steps: [
      'Add oats, chia and honey to a jar with a lid.',
      'Pour in the milk, seal, and shake hard for 10 seconds.',
      'Refrigerate at least 6 hours — overnight is ideal.',
      'Top with fruit right before eating so it stays fresh.',
    ],
    tip: 'Make three jars on Sunday night. They keep for four days in a mini fridge and free up your entire morning routine.',
    cuisine_region: 'American',
  },
  {
    slug: 'kettle-poached-eggs',
    title: 'Kettle-Poached Eggs',
    image: '/recipes/kettle-poached-eggs.jpg',
    minutes: 8,
    servings: 1,
    cost: '$0.60',
    costUSD: 0.60,
    difficulty: 'Medium',
    appliance: 'Kettle',
    meal: 'Breakfast',
    mealType: 'breakfast',
    countryTags: ['US'],
    blurb: 'Runny yolks from nothing but boiled water.',
    requiredAppliances: ['kettle'],
    dietary_tags: ['vegetarian', 'halal'],
    ingredients: [
      '2 eggs',
      'Boiling water from a kettle',
      '1 tsp vinegar',
      'Toast, salt, cracked pepper',
    ],
    steps: [
      'Boil a full kettle and pour it into a deep heatproof bowl or mug.',
      'Stir in the vinegar, then gently slide in one cracked egg.',
      'Cover with a plate and wait 4 minutes for a soft yolk, 6 for firm.',
      'Lift out with a spoon, drain, and serve on toast with salt and pepper.',
    ],
    tip: 'Crack the egg into a small cup first. Sliding it in gently keeps the white together instead of shredding into wisps.',
    cuisine_region: 'General',
  },
  {
    slug: 'upgraded-instant-ramen',
    title: 'Upgraded Instant Ramen',
    image: '/recipes/upgraded-ramen.jpg',
    minutes: 10,
    servings: 1,
    cost: '$1.20',
    costUSD: 1.20,
    difficulty: 'Easy',
    appliance: 'Hot plate',
    meal: 'Lunch',
    mealType: 'lunch',
    countryTags: ['JP', 'KR'],
    blurb: 'Four cheap additions turn a packet into a real bowl.',
    requiredAppliances: ['kettle'],
    dietary_tags: ['halal', 'contains_meat'],
    ingredients: [
      '1 pack instant ramen',
      '1 egg',
      '2 tbsp frozen corn',
      '1 scallion, sliced',
      '1 tsp chili oil',
      'Half the seasoning packet',
    ],
    steps: [
      'Boil 400ml water, add the noodles and corn, and cook for 2 minutes.',
      'Add only half the seasoning packet so the broth is not overly salty.',
      'Crack the egg into the middle and cover for 90 seconds.',
      'Slide everything into a bowl, then finish with scallions and chili oil.',
    ],
    tip: 'Half the seasoning plus a splash of soy sauce gives a rounder broth with far less sodium than the packet intends.',
    cuisine_region: 'Japanese',
  },
  {
    slug: 'skillet-quesadilla',
    title: 'Two-Minute Quesadilla',
    image: '/recipes/skillet-quesadilla.jpg',
    minutes: 6,
    servings: 1,
    cost: '$1.10',
    costUSD: 1.10,
    difficulty: 'Easy',
    appliance: 'Hot plate',
    meal: 'Snack',
    mealType: 'snack',
    countryTags: ['US', 'MX'],
    blurb: 'The 11pm study-session classic, done properly.',
    requiredAppliances: ['induction_burner'],
    dietary_tags: ['vegetarian', 'halal'],
    ingredients: [
      '1 large flour tortilla',
      '1/2 cup shredded cheese',
      '2 tbsp black beans',
      'Salsa for dipping',
    ],
    steps: [
      'Heat a dry pan over medium until a drop of water sizzles.',
      'Lay the tortilla flat, scatter cheese and beans over one half only.',
      'Fold over and press down. Cook 2 minutes per side until golden.',
      'Rest 1 minute before cutting so the cheese sets instead of running out.',
    ],
    tip: 'No pan? Two minutes in the microwave on a plate works — then 30 seconds under a hot plate lid to crisp the outside.',
    cuisine_region: 'American',
  },
]

export const profile = {
  name: '',
  school: '',
  dorm: 'Dorm Room',
  year: 'Freshman',
  initials: '',
  country: 'PH',
  timezone: 'Asia/Manila',
  appliances: ['microwave', 'kettle'] as ApplianceType[],
  dietary_preference: 'none' as DietaryPreference,
  dietary_note: '',
}

export const subjectColorClass: Record<SubjectColor, { bg: string; text: string; soft: string }> = {
  1: { bg: 'bg-subject-1', text: 'text-subject-1', soft: 'bg-subject-1/12' },
  2: { bg: 'bg-subject-2', text: 'text-subject-2', soft: 'bg-subject-2/12' },
  3: { bg: 'bg-subject-3', text: 'text-subject-3', soft: 'bg-subject-3/12' },
  4: { bg: 'bg-subject-4', text: 'text-subject-4', soft: 'bg-subject-4/12' },
  5: { bg: 'bg-subject-5', text: 'text-subject-5', soft: 'bg-subject-5/12' },
}

export function formatTime(t: string) {
  if (!t) return ''
  if (t.includes('AM') || t.includes('PM')) return t
  const [h, m] = t.split(':').map(Number)
  if (isNaN(h)) return t
  const period = h >= 12 ? 'PM' : 'AM'
  const hour = h % 12 === 0 ? 12 : h % 12
  return `${hour}:${String(m || 0).padStart(2, '0')} ${period}`
}

export function formatTimeRange(start: string, end: string) {
  if (!start) return ''
  const startStr = formatTime(start)
  if (!end) return startStr
  const endStr = formatTime(end)
  return `${startStr} – ${endStr}`
}

export function minutesOf(t: string) {
  const [h, m] = t.split(':').map(Number)
  return h * 60 + m
}
